changelog:
  categories:
    - title: Breaking changes
      labels:
        - breaking-changes
    - title: Dependencies
      labels:
        - dependencies
    - title: Changes
      labels:
        - "*"
